### ISSUE TITLE
couch_login && https doesn't support local cert/key

### ISSUE THREAD

**Issue by leecookson** [npm/couch-login#4]
I have a situation where a client cert+key is required to connect to our internal npm registry.  I see support up through tls, https and request, but here, only the server CA is supported.  It seems like adding support would be easy following the technique used by the "ca" config option.  I could offer a patch if necessary.  After this, I'm looking at the same issue with npm_registry_client.

**Comment by doublerebel** [comment]
Looks like this was closed with 378bdfcc.
